export const sitePreset = {
  managedDirectories: [
    'img/usa-icons',
    // Keep this folder even when app templates do not reference it directly.
    // USWDS compiled selectors still point at specific usa-icons-bg assets
    // (for example external alt links and emergency/checklist variants).
    'img/usa-icons-bg',
  ],
  managedFiles: [
    'fonts/merriweather/Latin-Merriweather-Bold.woff2',
    'fonts/merriweather/Latin-Merriweather-BoldItalic.woff2',
    'fonts/merriweather/Latin-Merriweather-Italic.woff2',
    'fonts/merriweather/Latin-Merriweather-Light.woff2',
    'fonts/merriweather/Latin-Merriweather-LightItalic.woff2',
    'fonts/merriweather/Latin-Merriweather-Regular.woff2',
    'fonts/public-sans/PublicSans-Bold.woff2',
    'fonts/public-sans/PublicSans-BoldItalic.woff2',
    'fonts/public-sans/PublicSans-Italic.woff2',
    'fonts/public-sans/PublicSans-Light.woff2',
    'fonts/public-sans/PublicSans-LightItalic.woff2',
    'fonts/public-sans/PublicSans-Regular.woff2',
    'fonts/roboto-mono/roboto-mono-v5-latin-300.woff2',
    'fonts/roboto-mono/roboto-mono-v5-latin-300italic.woff2',
    'fonts/roboto-mono/roboto-mono-v5-latin-700.woff2',
    'fonts/roboto-mono/roboto-mono-v5-latin-700italic.woff2',
    'fonts/roboto-mono/roboto-mono-v5-latin-italic.woff2',
    'fonts/roboto-mono/roboto-mono-v5-latin-regular.woff2',
    'img/checkbox-indeterminate-alt.svg',
    'img/checkbox-indeterminate.svg',
    'img/circle-124.png',
    'img/circle-gray-20.svg',
    'img/correct8-alt.svg',
    'img/correct8.svg',
    'img/file-excel.svg',
    'img/file-pdf.svg',
    'img/file-video.svg',
    'img/file-word.svg',
    'img/file.svg',
    'img/icon-dot-gov.svg',
    'img/icon-https.svg',
    'img/loader.gif',
    'img/loader.svg',
    'img/lock.svg',
    'img/logo-img.png',
    'img/sprite.svg',
    'img/us_flag.svg',
    'img/us_flag_small.png',
  ],
  managedLocalFiles: [
    {
      source: 'assets/hero.jpg',
      target: 'img/hero.jpg',
    },
    {
      source: 'assets/favicon.svg',
      target: 'favicon.svg',
    },
  ],
  prunePaths: [
    'fonts/merriweather',
    'fonts/public-sans',
    'fonts/roboto-mono',
    'fonts/source-sans-pro',
    'img/favicons',
    'img/material-icons',
    'img/material-icons-deprecated',
    'img/uswds-icons',
  ],
};
